[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "card-extractor"
version = "0.1.0"
description = "Card extractor project"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "openpyxl",
  "python-docx",
  "requests",
  "streamlit",
]
